<?php

/**
 * @file
 * Contains sky_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sky_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sky_migrate module.
    case 'help.page.sky_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Migrate') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function sky_migrate_migration_plugins_alter(&$definitions) {
//  $definitions['migrate_csv']['source']['path'] = drupal_get_path('module', 'sky_migrate') . $definitions['migrate_csv']['source']['path'];
}
